export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const SELECT_ITEM_SIZE = 'SELECT_ITEM_SIZE';
export const SELECT_ITEM_COLOR = 'SELECT_ITEM_COLOR';
export const DELETE_ALL_CARTITEM = 'DELETE_ALL_CARTITEM';
export const RESET_STATES = 'RESET_STATES';
